### ISSUE TITLE
missing DQN_multi_head.py

### ISSUE THREAD

**Issue by abcwen** [NishanthVAnand/prediction_and_control_in_continual_reinforcement_learning#1]
run bash run_minatar.sh
python: can't open file './control/minatar_crl/DQN_multi_head.py': [Errno 2] No such file or directory

**Comment by NishanthVAnand** [comment]
The file name is `DQN_multi_task.py` not `DQN_multi_head.py`. I’ve updated the run file to reflect the same.

**Comment by abcwen** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我已经收到信件。
